/*
******************************************************************************
File:     tiny_printf.c
Info:     Generated by Atollic TrueSTUDIO 9.0.1   2018-10-17

Abstract: Atollic TrueSTUDIO Minimal iprintf/siprintf/fiprintf
          and puts/fputs.
          Provides aliased declarations for printf/sprintf/fprintf
          pointing to *iprintf variants.

          The argument contains a format string that may include
          conversion specifications. Each conversion specification
          is introduced by the character %, and ends with a
          conversion specifier.

          The following conversion specifiers are supported
          cdisuxX%

          Usage:
          c    character
          d,i  signed integer (-sign added, + sign not supported)
          s    character string
          u    unsigned integer as decimal
          x,X  unsigned integer as hexadecimal (uppercase letter)
          %    % is written (conversion specification is '%%')

          Note:
          Character padding is not supported

The MIT License (MIT)
Copyright (c) 2018 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/
#define MAXLN 256
/* Includes */
#include <stdarg.h>
#include <stdio.h>
#include <string.h>
#include <ctype.h>

/* Create aliases for *printf to integer variants *iprintf */
__attribute__ ((alias("iprintf"))) int printf(const char *fmt, ...);
__attribute__ ((alias("fiprintf"))) int fprintf(FILE* fp, const char *fmt, ...);
__attribute__ ((alias("siprintf"))) int sprintf(char* str, const char *fmt, ...);

/* External function prototypes (defined in syscalls.c) */
extern int _write(int fd, char *str, int len);

/* Private function prototypes */
void ts_itoa(char **buf, unsigned int d, int base);
int ts_formatstring(char *buf, const char *fmt, va_list va);
int ts_formatlength(const char *fmt, va_list va);

/* Private functions */
/**
**---------------------------------------------------------------------------
**  Abstract: Convert integer to ascii
**  Returns:  void
**---------------------------------------------------------------------------
*/
void ts_itoa(char **buf, unsigned int d, int base)
{
	int div = 1;
	while (d/div >= base)
		div *= base;

	while (div != 0)
	{
		int num = d/div;
		d = d%div;
		div /= base;
		if (num > 9)
			*((*buf)++) = (num-10) + 'A';
		else
			*((*buf)++) = num + '0';
	}
}

/**
**---------------------------------------------------------------------------
**  Abstract: Writes arguments va to buffer buf according to format fmt
**  Returns:  Length of string
**---------------------------------------------------------------------------
*/
int ts_formatstring(char *buf, const char *fmt, va_list va)
{
	char *start_buf = buf;
	while(*fmt)
	{
		/* Character needs formating? */
		if (*fmt == '%')
		{
			switch (*(++fmt))
			{
			  case 'c':
				*buf++ = va_arg(va, int);
				break;
			  case 'd':
			  case 'i':
				{
					signed int val = va_arg(va, signed int);
					if (val < 0)
					{
						val *= -1;
						*buf++ = '-';
					}
					ts_itoa(&buf, val, 10);
				}
				break;
			  case 's':
				{
					char * arg = va_arg(va, char *);
					while (*arg)
					{
						*buf++ = *arg++;
					}
				}
				break;
			  case 'u':
					ts_itoa(&buf, va_arg(va, unsigned int), 10);
				break;
			  case 'x':
			  case 'X':
					ts_itoa(&buf, va_arg(va, int), 16);
				break;
			  case '%':
				  *buf++ = '%';
				  break;
			}
			fmt++;
		}
		/* Else just copy */
		else
		{
			*buf++ = *fmt++;
		}
	}
	*buf = 0;

	return (int)(buf - start_buf);
}


/**
**---------------------------------------------------------------------------
**  Abstract: Calculate maximum length of the resulting string from the
**            format string and va_list va
**  Returns:  Maximum length
**---------------------------------------------------------------------------
*/
int ts_formatlength(const char *fmt, va_list va)
{
	int length = 0;
	while (*fmt)
	{
		if (*fmt == '%')
		{
			++fmt;
			switch (*fmt)
			{
			  case 'c':
		  		  va_arg(va, int);
				  ++length;
				  break;
			  case 'd':
			  case 'i':
			  case 'u':
				  /* 32 bits integer is max 11 characters with minus sign */
				  length += 11;
				  va_arg(va, int);
				  break;
			  case 's':
			  	  {
			  		  char * str = va_arg(va, char *);
			  		  while (*str++)
			  			  ++length;
			  	  }
				  break;
			  case 'x':
			  case 'X':
				  /* 32 bits integer as hex is max 8 characters */
				  length += 8;
				  va_arg(va, unsigned int);
				  break;
			  default:
				  ++length;
				  break;
			}
		}
		else
		{
			++length;
		}
		++fmt;
	}
	return length;
}

/**
**===========================================================================
**  Abstract: Loads data from the given locations and writes them to the
**            given character string according to the format parameter.
**  Returns:  Number of bytes written
**===========================================================================
*/
int siprintf(char *buf, const char *fmt, ...)
{
	int length;
	va_list va;
	va_start(va, fmt);
	length = ts_formatstring(buf, fmt, va);
	va_end(va);
	return length;
}

/**
**===========================================================================
**  Abstract: Loads data from the given locations and writes them to the
**            given file stream according to the format parameter.
**  Returns:  Number of bytes written
**===========================================================================
*/
int fiprintf(FILE * stream, const char *fmt, ...)
{
	int length = 0;
	va_list va;
	va_start(va, fmt);
	length = ts_formatlength(fmt, va);
	va_end(va);
	{
		char buf[length];
		va_start(va, fmt);
		length = ts_formatstring(buf, fmt, va);
		length = _write(stream->_file, buf, length);
		va_end(va);
	}
	return length;
}

/**
**===========================================================================
**  Abstract: Loads data from the given locations and writes them to the
**            standard output according to the format parameter.
**  Returns:  Number of bytes written
**
**===========================================================================
*/
int iprintf(const char *fmt, ...)
{
	int length = 0;
	va_list va;
	va_start(va, fmt);
	length = ts_formatlength(fmt, va);
	va_end(va);
	{
		char buf[length];
		va_start(va, fmt);
		length = ts_formatstring(buf, fmt, va);
		length = _write(1, buf, length);
		va_end(va);
	}
	return length;
}

/**
**===========================================================================
**  Abstract: fputs writes the string at s (but without the trailing null) to
**  the file or stream identified by fp.
**  Returns:  If successful, the result is 0; otherwise, the result is EOF.
**
**===========================================================================
*/
int fputs(const char *s, FILE *fp)
{
	int length = strlen(s);
	int wlen = 0;
	int res;

	wlen = _write((fp->_file), (char*)s, length);
	wlen += _write((fp->_file), "\n", 1);

	if (wlen == (length+1))
	{
		res = 0;
	}
	else
	{
		res = EOF;
	}

	return res;
}

/**
**===========================================================================
**  Abstract: puts writes the string at s (followed by a newline, instead of
**  the trailing null) to the standard output stream.
**  Returns:  If successful, the result is a nonnegative integer; otherwise,
**  the result is EOF.
**
**===========================================================================
*/
int puts(const char *s)
{
	int length = strlen(s);
	int numbytes = 0;
	int res;

	numbytes = _write(1, (char*)s, length);
	numbytes += _write(1, "\n", 1);

	if (numbytes == (length+1))
	{
		res = 0;
	}
	else
	{
		res = EOF;
	}

	return res;
}

/**
**===========================================================================
**  Abstract: Copy, starting from the memory location buf, count elements
**  (each of size size) into the file or stream identified by fp.
**  Returns:  Number of elements written
**
**===========================================================================
*/
size_t fwrite(const void * buf, size_t size, size_t count, FILE * fp)
{
	return (_write((fp->_file), (char*)buf, size * count) / size);
}


/*
 * ** fscanf --\    sscanf --\
 * **          |                  |
 * **  scanf --+-- vfscanf ----- vsscanf
 * **
 * ** This not been very well tested.. it probably has bugs
 */
int vfscanf __P((FILE *, const char *, va_list));
int vsscanf __P((const char *, const char *, va_list));

#define ISSPACE " \t\n\r\f\v"

/*
 *  scanf(fmt,va_alist)
 */
int
scanf (const char *fmt, ...)
{
    int             count;
    va_list ap;

    va_start (ap, fmt);
    count = vfscanf (stdin, fmt, ap);
    va_end (ap);
    return (count);
}

/*
 *  fscanf(fp,fmt,va_alist)
 */
int
fscanf (FILE *fp, const char *fmt, ...)
{
    int             count;
    va_list ap;

    va_start (ap, fmt);
    count = vfscanf (fp, fmt, ap);
    va_end (ap);
    return (count);
}

/*
 *  sscanf(buf,fmt,va_alist)
 */
int
sscanf (const char *buf, const char *fmt, ...)
{
    int             count;
    va_list ap;

    va_start (ap, fmt);
    count = vsscanf (buf, fmt, ap);
    va_end (ap);
    return (count);
}

/*
 *  vfscanf(fp,fmt,ap)
 */
 int
vfscanf (FILE *fp, const char *fmt, va_list ap)
{
    int             count;
    char            buf[MAXLN + 1];

    if (fgets (buf, MAXLN, fp) == 0)
	return (-1);
    count = vsscanf (buf, fmt, ap);
    return (count);
}


/*
 *  vsscanf(buf,fmt,ap)
 */
 int
vsscanf (const char *buf, const char *s, va_list ap)
{
    int             count, noassign, width, base, lflag;
    const char     *tc;
    char           *t, tmp[MAXLN];

    count = noassign = width = lflag = 0;
    while (*s && *buf) {
	while (isspace (*s))
	    s++;
	if (*s == '%') {
	    s++;
	    for (; *s; s++) {
		if (strchr ("dibouxcsefg%", *s))
		    break;
		if (*s == '*')
		    noassign = 1;
		else if (*s == 'l' || *s == 'L')
		    lflag = 1;
		else if (*s >= '1' && *s <= '9') {
		    for (tc = s; isdigit (*s); s++);
		    strncpy (tmp, tc, s - tc);
		    tmp[s - tc] = '\0';
		    atob (&width, tmp, 10);
		    s--;
		}
	    }
	    if (*s == 's') {
		while (isspace (*buf))
		    buf++;
		if (!width)
		    width = strcspn (buf, ISSPACE);
		if (!noassign) {
		    strncpy (t = va_arg (ap, char *), buf, width);
		    t[width] = '\0';
		}
		buf += width;
	    } else if (*s == 'c') {
		if (!width)
		    width = 1;
		if (!noassign) {
		    strncpy (t = va_arg (ap, char *), buf, width);
		    t[width] = '\0';
		}
		buf += width;
	    } else if (strchr ("dobxu", *s)) {
		while (isspace (*buf))
		    buf++;
		if (*s == 'd' || *s == 'u')
		    base = 10;
		else if (*s == 'x')
		    base = 16;
		else if (*s == 'o')
		    base = 8;
		else if (*s == 'b')
		    base = 2;
		if (!width) {
		    if (isspace (*(s + 1)) || *(s + 1) == 0)
			width = strcspn (buf, ISSPACE);
		    else
			width = strchr (buf, *(s + 1)) - buf;
		}
		strncpy (tmp, buf, width);
		tmp[width] = '\0';
		buf += width;
		if (!noassign)
		    atob (va_arg (ap, u_int32_t *), tmp, base);
	    }
	    if (!noassign)
		count++;
	    width = noassign = lflag = 0;
	    s++;
	} else {
	    while (isspace (*buf))
		buf++;
	    if (*s != *buf)
		break;
	    else
		s++, buf++;
	}
    }
    return (count);
}


 static char * _getbase __P((char *, int *));
 #ifdef HAVE_QUAD
 static int _atob __P((unsigned long long *, char *p, int));
 #else
 static int _atob __P((unsigned long  *, char *, int));
 #endif

 static char *
 _getbase(char *p, int *basep)
 {
 	if (p[0] == '0') {
 		switch (p[1]) {
 		case 'x':
 			*basep = 16;
 			break;
 		case 't': case 'n':
 			*basep = 10;
 			break;
 		case 'o':
 			*basep = 8;
 			break;
 		default:
 			*basep = 10;
 			return (p);
 		}
 		return (p + 2);
 	}
 	*basep = 10;
 	return (p);
 }


 /*
  *  _atob(vp,p,base)
  */
 static int
 #ifdef HAVE_QUAD
 _atob (u_quad_t *vp, char *p, int base)
 {
 	u_quad_t value, v1, v2;
 #else
 _atob (unsigned long *vp, char *p, int base)
 {
 	u_long value, v1, v2;
 #endif
 	char *q, tmp[20];
 	int digit;

 	if (p[0] == '0' && (p[1] == 'x' || p[1] == 'X')) {
 		base = 16;
 		p += 2;
 	}

 	if (base == 16 && (q = strchr (p, '.')) != 0) {
 		if (q - p > sizeof(tmp) - 1)
 			return (0);

 		strncpy (tmp, p, q - p);
 		tmp[q - p] = '\0';
 		if (!_atob (&v1, tmp, 16))
 			return (0);

 		q++;
 		if (strchr (q, '.'))
 			return (0);

 		if (!_atob (&v2, q, 16))
 			return (0);
 		*vp = (v1 << 16) + v2;
 		return (1);
 	}

 	value = *vp = 0;
 	for (; *p; p++) {
 		if (*p >= '0' && *p <= '9')
 			digit = *p - '0';
 		else if (*p >= 'a' && *p <= 'f')
 			digit = *p - 'a' + 10;
 		else if (*p >= 'A' && *p <= 'F')
 			digit = *p - 'A' + 10;
 		else
 			return (0);

 		if (digit >= base)
 			return (0);
 		value *= base;
 		value += digit;
 	}
 	*vp = value;
 	return (1);
 }

 /*
  *  atob(vp,p,base)
  *      converts p to binary result in vp, rtn 1 on success
  */
 int
 atob(u_int32_t *vp, char *p, int base)
 {
 #ifdef HAVE_QUAD
 	u_quad_t v;
 #else
 	u_long  v;
 #endif

 	if (base == 0)
 		p = _getbase (p, &base);
 	if (_atob (&v, p, base)) {
 		*vp = v;
 		return (1);
 	}
 	return (0);
 }


 #ifdef HAVE_QUAD
 /*
  *  llatob(vp,p,base)
  *      converts p to binary result in vp, rtn 1 on success
  */
 int
 llatob(u_quad_t *vp, char *p, int base)
 {
 	if (base == 0)
 		p = _getbase (p, &base);
 	return _atob(vp, p, base);
 }
 #endif


 /*
  *  char *btoa(dst,value,base)
  *      converts value to ascii, result in dst
  */
 char *
 btoa(char *dst, u_int value, int base)
 {
 	char buf[34], digit;
 	int i, j, rem, neg;

 	if (value == 0) {
 		dst[0] = '0';
 		dst[1] = 0;
 		return (dst);
 	}

 	neg = 0;
 	if (base == -10) {
 		base = 10;
 		if (value & (1L << 31)) {
 			value = (~value) + 1;
 			neg = 1;
 		}
 	}

 	for (i = 0; value != 0; i++) {
 		rem = value % base;
 		value /= base;
 		if (rem >= 0 && rem <= 9)
 			digit = rem + '0';
 		else if (rem >= 10 && rem <= 36)
 			digit = (rem - 10) + 'a';
 		buf[i] = digit;
 	}

 	buf[i] = 0;
 	if (neg)
 		strcat (buf, "-");

 	/* reverse the string */
 	for (i = 0, j = strlen (buf) - 1; j >= 0; i++, j--)
 		dst[i] = buf[j];
 	dst[i] = 0;
 	return (dst);
 }

 #ifdef HAVE_QUAD
 /*
  *  char *btoa(dst,value,base)
  *      converts value to ascii, result in dst
  */
 char *
 llbtoa(char *dst, u_quad_t value, int base)
 {
 	char buf[66], digit;
 	int i, j, rem, neg;

 	if (value == 0) {
 		dst[0] = '0';
 		dst[1] = 0;
 		return (dst);
 	}

 	neg = 0;
 	if (base == -10) {
 		base = 10;
 		if (value & (1LL << 63)) {
 			value = (~value) + 1;
 			neg = 1;
 		}
 	}

 	for (i = 0; value != 0; i++) {
 		rem = value % base;
 		value /= base;
 		if (rem >= 0 && rem <= 9)
 			digit = rem + '0';
 		else if (rem >= 10 && rem <= 36)
 			digit = (rem - 10) + 'a';
 		buf[i] = digit;
 	}

 	buf[i] = 0;
 	if (neg)
 		strcat (buf, "-");

 	/* reverse the string */
 	for (i = 0, j = strlen (buf) - 1; j >= 0; i++, j--)
 		dst[i] = buf[j];
 	dst[i] = 0;
 	return (dst);
 }
 #endif

 /*
  *  gethex(vp,p,n)
  *      convert n hex digits from p to binary, result in vp,
  *      rtn 1 on success
  */
 int
 gethex(int32_t *vp, char *p, int n)
 {
 	u_long v;
 	int digit;

 	for (v = 0; n > 0; n--) {
 		if (*p == 0)
 			return (0);
 		if (*p >= '0' && *p <= '9')
 			digit = *p - '0';
 		else if (*p >= 'a' && *p <= 'f')
 			digit = *p - 'a' + 10;
 		else if (*p >= 'A' && *p <= 'F')
 			digit = *p - 'A' + 10;
 		else
 			return (0);

 		v <<= 4;
 		v |= digit;
 		p++;
 	}
 	*vp = v;
 	return (1);
 }
